package org.scapy.core.event;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Indicates that the annotated type of event was observed by polling (that is,
 * regular checking) rather than by being generated by the source at the exact
 * time of occurrence.
 *
 * @author Martin Tuskevicius
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface PolledEvent {

}